### ISSUE TITLE
Gridlines that transition

### ISSUE THREAD

**Issue by henryjameslau** [ONSvisual/svelte-charts#1]
Can you get the axis and gridlines to transition too

**Comment by jtrim-ons** [comment]
That would be cool! I did a bit of Googling and didn't come across any examples of people doing this with LayerCake or Svelte. Maybe the easiest way would be to add all the tick marks that you might possibly need ahead of time, then show/hide the one you need when you animate it???

**Comment by bothness** [comment]
@henryjameslau I figured out an approach to this on the latest version. Basically if you tween the extents of xDomain or yDomain, then the xScale/yScale function also gets tweened, so the axes get tweened for free.
