### ISSUE TITLE
scaleTime for line charts

### ISSUE THREAD

**Issue by henryjameslau** [ONSvisual/svelte-charts#7]
<img width="343" alt="image" src="https://user-images.githubusercontent.com/2945099/216163735-ca22cbf5-4ad5-4b16-91de-ce8720848c7b.png">
<img width="680" alt="image" src="https://user-images.githubusercontent.com/2945099/216163775-2798a2e7-47c3-49db-8ef3-c3b2ae5e096d.png">
I'm getting some weird stuff on the x-axis because I'm passing in values as date so I think we need a prop for xScale like we do for yScale.

**Comment by bothness** [comment]
I think this has now implemented. @henryjameslau pls re-open this if I'm wrong.
