### ISSUE TITLE
scaling/wrapping long tick labels (especially on smaller screen sizes)

### ISSUE THREAD

**Issue by ananmaysharan** [ONSvisual/svelte-charts#9]
I'm not currently aware of a way to scale or wrap the tick labels on chart axes when their length is such that the labels start to overlap. I realize this is hard to do especially with svg <text> elements, but was just wondering if this was planned in any way, or whether there was a current way to wrap or break the labels, or even reduce their font size.

I've attached a screenshot of an example of the overlapping labels: 

![image](https://github.com/ONSvisual/svelte-charts/assets/32856566/f4f5ef79-96b1-422c-9608-274f4250a000)

cheers!

**Comment by bothness** [comment]
Hi @ananmaysharan - We've now implemented label wrapping by default for the y-axis label on the BarChart (horizontal bars) component, and for inline labels on the LineChart and ScatterChart components. For your use-case I'd recommend either using BarChart, or using a ColumnChart with shortened labels (eg. Sun, Mon etc in this example).

FYI, you can also override the CSS on the charts (eg. font-size) by targeting the classes of the axes etc.
